title: PNWKeyboards
url: https://www.pnwkeyboards.com # No trailing slash in the url!
description: Custom mechanical keyboards from the Pacific Northwest.

og:
  image: /assets/images/thumbnail.png
  secure_image: /assets/images/thumbnail.png
  image_mimetype: image/png
  image_width: 1200
  image_height: 350
  image_alt: The PNWKeyboards Logo
twitter:
  username: "@pnwkeyboards"

google_analytics: "UA-173246992-1"

snipcart:
  api_key: N2VmM2ExZDQtZjhhMS00Y2Y1LWI1MWMtZjAwOTE1NTY0YjgzNjM3MzA5OTIyOTE1NzYzNjk0

collections:
  shop:
    output: true

exclude:
  - start_local.sh

plugins:
  - jekyll-feed
  - jekyll-sitemap
